/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihan;

public class App {
    public double kali(double operandA,double operandB){
        return operandA*operandB;
    }
    
    public double bagi(double operandA,double operandB){
        return operandA/operandB;
    }
    
    public double tambah(double operandA,double operandB){
        return operandA+operandB;
    }
    
    public double kurang(double operandA,double operandB){
        return operandA-operandB;
    }

    public static void main(String[] args) {
        App hitung = new App();
        System.out.println(hitung.kali(2, 5));
        System.out.println(hitung.bagi(2, 2));
        System.out.println(hitung.tambah(2, 2));
        System.out.println(hitung.kurang(2, 1));
    }
}
