/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package concurrent;

/*
class MyTask{
    void excuteTask(){
        for(int doc=1;doc<=10;doc++){
            System.out.println("@@ Printing Document #"+doc+" - printer 2");
        }
    }
}
*/
/* 
class MyTask extends Thread{
    @Override
    public void run(){
        for(int doc=1;doc<=10;doc++){
            System.out.println("@@ Printing Document #"+doc+" - printer 2");
        }
    }
}
*/
class CA{

}

class MyTask extends CA implements Runnable{
    @Override
    public void run(){
        for(int doc=1;doc<=10;doc++){
            System.out.println("@@ Printing Document #"+doc+" - printer 2");
        }
    }
}

class YourTask implements Runnable{
    @Override
    public void run(){
        for(int doc=1;doc<=10;doc++){
            System.out.println("** Printing Document #"+doc+" - printer 3");
        }
    }
}

public class App {

    public static void main(String[] args) {
        
        //job 1
        System.out.println("===Application Start===");

        //job 2
        /*
        MyTask task = new MyTask();
        task.excuteTask();
        */

        /*
        MyTask task = new MyTask();
        task.start();
        */
        Runnable r = new MyTask();
        Thread task = new Thread(r);
        task.start();

        Thread YourTask = new Thread(new YourTask());
        //task.setDaemon(True);
        YourTask.start();

        //new Thread(new YourTask()).start();

        //job 3
        for(int doc=1;doc<=10;doc++){
            System.out.println("^^ Printing Document #"+doc+" - printer 1");
        }

        //job 4
        System.out.println("===Application Finish===");
    }
}